"""
clinical_report_engine.py
-------------------------
Generates clinical-style PDF reports for patient risk predictions.
"""

import os
from datetime import datetime

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer


class ClinicalReportEngine:
    """Builds a patient-level clinical PDF report."""

    def __init__(self, output_dir="reports/clinical"):
        self.output_dir = output_dir
        os.makedirs(self.output_dir, exist_ok=True)

    def generate(self, patient_id, probability, risk_level, top_features=None):
        """
        Create a PDF report and return its file path.

        top_features: iterable of (feature_name, shap_impact) pairs.
        """
        path = os.path.join(self.output_dir, f"patient_{patient_id}_report.pdf")

        doc = SimpleDocTemplate(path)
        styles = getSampleStyleSheet()
        story = [
            Paragraph("<b>Heart Disease Clinical Report</b>", styles["Title"]),
            Spacer(1, 12),
            Paragraph(f"Generated: {datetime.now():%Y-%m-%d %H:%M}", styles["Normal"]),
            Paragraph(f"Patient ID: {patient_id}", styles["Normal"]),
            Paragraph(f"Risk Probability: {probability:.2f}", styles["Normal"]),
            Paragraph(f"Risk Level: {risk_level.upper()}", styles["Normal"]),
            Spacer(1, 12),
        ]

        if top_features:
            story.append(Paragraph("<b>Key Contributing Factors:</b>", styles["Normal"]))
            for name, impact in top_features:
                direction = "increases" if impact > 0 else "decreases"
                story.append(Paragraph(f"• {name} {direction} risk", styles["Normal"]))

        story.append(Spacer(1, 24))
        story.append(Paragraph(
            "<i>This report is generated by a decision-support system and "
            "does not replace professional medical judgment.</i>",
            styles["Normal"],
        ))

        doc.build(story)
        return path